[kafka]
brokers = ['localhost:9092']
username = ''
password = ''
server_name = ''
partition = 2
replication = 1

[mysql]
    [mysql.event]
        host = '127.0.0.1'
        port = 3306
        user = 'root'
        password = '123456'
        db = 'betradar'
        max_open_conns = 2
        ssl_mode = 'disable' # disable | require ï½œ verify-ca
        # ssl_root_cert = '/path/to/redshift-ca.pem'